# NeON Build File (http://github.com/c4s4/neon)

default: run
extends: golang

properties:
  NAME:    'dvdrental'
  VERSION: '1.0.0'
  LIBRARIES:
  - 'github.com/gin-gonic/gin'
  - 'github.com/lib/pq'
  - 'gopkg.in/yaml.v2'

environment:
  DBHOST: 'localhost'
  DBPORT: '5432'
  DBUSER: 'postgres'
  DBPASS: 'postgres'
  DBNAME: 'dvdrental'

targets:

  client:
    doc: Run benchmark client
    steps:
    - time:
      - $: ['go', 'run', 'client.go', 'http://localhost:8080/food/']
