# NeON build file (http://github.com/c4s4/neon)

extends: golang
default: [fmt, check, test]
expose:  [fmt, check, test, release]
configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

properties:
  NAME:    'dvdrental'
  PACKAGE: '.'
  LIBRARIES:
  - 'github.com/gin-gonic/gin'
  - 'github.com/lib/pq'
  - 'gopkg.in/yaml.v2'

environment:
  DBHOST: 'localhost'
  DBPORT: '5432'
  DBNAME: 'dvdrental'
  DBUSER: 'postgres'
  DBPASS: ''

targets:

  actors:
    doc: Run actor client
    steps:
    - time:
      - $: ['go', 'run', 'client/main.go', 'actor', '200']

  films:
    doc: Run film client
    steps:
    - time:
      - $: ['go', 'run', 'client/main.go', 'film', '1000']
